name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Verify Cypress files exist
        run: |
          echo "=== Checking for Cypress test files ==="
          pwd
          echo "Current directory contents:"
          ls -la
          echo "Cypress directory:"
          ls -la cypress/ || echo "cypress/ directory not found"
          echo "Cypress e2e directory:"
          ls -la cypress/e2e/ || echo "cypress/e2e/ directory not found"
          echo "Looking for .cy.js files:"
          find . -name "*.cy.js" -type f || echo "No .cy.js files found"
          echo "Cypress config file:"
          ls -la cypress.config.js || echo "cypress.config.js not found"
          
      - name: Debug Cypress installation
        run: |
          echo "=== Cypress Debug Info ==="
          npx cypress version
          npx cypress verify
      
      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # Don't install again since we already did npm ci
          install: false
          # Starts web server for E2E tests
          start: npm start
          wait-on: 'http://localhost:3000'
          # Records to Cypress Cloud 
          record: true
          parallel: false # Disable parallel for debugging
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Test against locally started server
          CYPRESS_BASE_URL: http://localhost:3000