name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      # Optionally, run Cypress E2E tests
      # - name: Run Cypress tests
      #   uses: cypress-io/github-action@v6

      # Optionally, deploy to Render or another host
      # (see Render docs for deployment via GitHub Actions)