name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install  # Changed from npm ci

      - name: Run unit tests
        run: npm run test:run

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'https://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
        env:  
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          CYPRESS_baseUrl: https://localhost:3000
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_NODE_ENV: ${{ secrets.VITE_NODE_ENV }}
          NODE_ENV: production

      # Optionally, deploy to Render or another host
      # (see Render docs for deployment via GitHub Actions)